apiVersion: 1

datasources:
- name: Loki
  type: loki
  uid: loki
  access: proxy
  url: http://common_loki:3100
  jsonData:
    derivedFields:
      - datasourceUid: tempo
        name: traceId
        matcherRegex: "^.*?traceI[d|D]=(\\w+).*$"
        url: '$${__value.raw}'
      - datasourceUid: tempo
        name: trace_id
        matcherType: "label"
        matcherRegex: "trace_id"
        url: '$${__value.raw}'

- name: Tempo
  type: tempo
  uid: tempo
  access: proxy
  url: http://common_tempo:3200
