apiVersion: 1

datasources:
- name: Loki
  type: loki
  uid: loki
  access: proxy
  url: http://loki:3100
  jsonData:
    derivedFields:
      - datasourceUid: tempo
        name: trace_id
        matcherType: "label"
        matcherRegex: "trace_id"
        url: '$${__value.raw}'

- name: Mimir
  type: prometheus
  uid: mimir
  access: proxy
  url: http://mimir:9009/prometheus
  jsonData:
    exemplarTraceIdDestinations:
      - datasourceUid: tempo
        name: trace_id
    httpMethod: POST
    timeInterval: "2s"

- name: Tempo
  type: tempo
  uid: tempo
  access: proxy
  url: http://tempo:3200
  jsonData:
    tracesToLogs:
      datasourceUid: loki
      filterByTraceID: false
      spanEndTimeShift: "500ms"
      spanStartTimeShift: "-500ms"
      tags: ['dummy']
